sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t smshss/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true smshss/docker-react npm run test